# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wished_by',
        ),
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(related_name='wished_item', to='first_app.User'),
        ),
    ]
