# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-24 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_item_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wished_by',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
