# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='item',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='uploader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='first_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(max_length=255),
        ),
    ]
