# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20180425_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quoted_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorited_by',
            field=models.ManyToManyField(related_name='fav_quotes', to='first_app.User'),
        ),
    ]
